In [1]:
%cd ~/repo/protein-transfer

/home/t-fli/repo/protein-transfer


In [2]:
%load_ext blackcellmagic

In [ ]:
from scr.preprocess.data_process import TaskProcess

In [10]:
TaskProcess().sum_file_df

task              dataset        split  \
0  annotation                  scl     balanced   
1   structure  secondary_structure        cb513   
2      proeng                  gb1  two_vs_rest   
3      proeng                  gb1  low_vs_high   
4      proeng                  aav  one_vs_many   
5      proeng                  aav  two_vs_many   
6      proeng               thermo        mixed   

                                            csv_path  \
0                   data/annotation/scl/balanced.csv   
1  [data/structure/secondary_structure/secondary_...   
2                    data/proeng/gb1/two_vs_rest.csv   
3                    data/proeng/gb1/low_vs_high.csv   
4                    data/proeng/aav/one_vs_many.csv   
5                    data/proeng/aav/two_vs_many.csv   
6                       data/proeng/thermo/mixed.csv   

                     fasta_path                         pkl_path  
0                                                                 
1                                                                 
2  data/proeng/gb1/5LDE_1.fasta  data/proeng/gb1/two_vs_rest.pkl  
3  data/proeng/gb1/5LDE_1.fasta  data/proeng/gb1/low_vs_high.pkl  
4  data/proeng/aav/P03135.fasta  data/proeng/aav/one_vs_many.pkl  
5  data/proeng/aav/P03135.fasta  data/proeng/aav/two_vs_many.pkl  
6

In [3]:
from scr.preprocess.data_process import ProtranDataset

In [5]:
from scr.encoding.encoding_classes import ESMEncoder

In [6]:
encoder = ESMEncoder

In [7]:
dataset_path="data/proeng/gb1/two_vs_rest.pkl"
val_dataset = ProtranDataset(dataset_path=dataset_path, 
                             subset="val",
                             encoder_class=ESMEncoder,
                             encoder_name="esm1b_t33_650M_UR50S",
                             embed_layer=0,
                             embed_batch_size=32,
                             flatten_emb="mean",
                             embed_path=None)

Loading esm1b_t33_650M_UR50S using 0 layer embedding


Using cache found in /home/t-fli/.cache/torch/hub/facebookresearch_esm_main
100%|██████████| 2/2 [00:32<00:00, 16.47s/it]


In [8]:
len(val_dataset), val_dataset[0], val_dataset[0][0].shape

(43,
 (tensor([-0.1774, -0.0007,  0.0167,  ...,  0.0066,  0.0361,  0.0965]),
  1.80292279874,
  'MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVNGEWTYDDATKTFTVTELEVLFQGPLDPNSMATYEVLCEVARKLGTDDREVVLFLLNVFIPQPTLAQLIGALRALKEEGRLTFPLLAECLFRAGRRDLLRDLLHLDPRFLERHLAGTMSYFSPYQLTVLHVDGELCARDIRSLIFLSKDTIGSRSTPQTFLHWVYCMENLDLLGPTDVDALMSMLRSLSRVDLQRQVQTLMGLHLSGPSHSQHYRHTPLEHHHHHH',
  'D40N',
  1),
 torch.Size([1280]))

In [11]:
from torch.utils.data import DataLoader

In [12]:
val_loader = DataLoader(
            dataset=val_dataset,
            batch_size=32,
            shuffle=False,
            worker_init_fn=42,
        )

In [15]:
for (x, y, sequence, mut_name, mut_numb) in val_loader:
    print(x, y)

tensor([[-0.1774, -0.0007,  0.0167,  ...,  0.0066,  0.0361,  0.0965],
        [-0.1748, -0.0007,  0.0166,  ...,  0.0063,  0.0378,  0.0964],
        [-0.1749, -0.0006,  0.0168,  ...,  0.0066,  0.0395,  0.0966],
        ...,
        [-0.1766, -0.0007,  0.0166,  ...,  0.0063,  0.0361,  0.0966],
        [-0.1775, -0.0007,  0.0165,  ...,  0.0063,  0.0366,  0.0968],
        [-0.1771,  0.0002,  0.0165,  ...,  0.0065,  0.0362,  0.0964]]) tensor([1.8029e+00, 7.1123e-01, 8.6005e-01, 6.1898e-01, 2.2602e+00, 1.7291e+00,
        1.7197e+00, 2.2677e+00, 1.7626e+00, 2.3160e-01, 6.1434e-01, 6.1031e-01,
        1.0339e+00, 5.1069e-01, 6.9899e-01, 1.8930e+00, 0.0000e+00, 6.9803e-01,
        5.9696e-01, 1.1877e+00, 9.7038e-01, 5.5813e-01, 4.1580e+00, 8.5351e-01,
        6.0882e-01, 1.0669e+00, 1.7081e+00, 3.0943e+00, 2.9738e-03, 7.3959e-02,
        1.9298e+00, 1.9539e+00], dtype=torch.float64)
tensor([[-0.1768, -0.0007,  0.0165,  ...,  0.0065,  0.0366,  0.0965],
        [-0.1752, -0.0007,  0.0166,  ..., 

In [16]:
x.shape, y.shape

(torch.Size([11, 1280]), torch.Size([11]))

In [21]:
sequence[0][:56], sequence[0][38],  sequence[0][39], sequence[0][40], sequence[0][53]

('MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVIGEWTYDDATKTFTGTE',
 'V',
 'I',
 'G',
 'G')

In [22]:
mut_name[0], mut_numb[0]

('D40I:V54G', tensor(2))

In [63]:
dataset_path="data/proeng/gb1/two_vs_rest.pkl"
val_dataset = ProtranDataset(dataset_path=dataset_path, 
                             subset="val",
                             encoder_class=ESMEncoder,
                             encoder_name="esm1b_t33_650M_UR50S",
                             embed_layer=0,
                             embed_batch_size=32,
                             flatten_emb="mean",
                             embed_path=None,
                             seq_start_idx = False,
                             seq_end_idx = 56,)

0 56
Loading esm1b_t33_650M_UR50S using 0 layer embedding


Using cache found in /home/t-fli/.cache/torch/hub/facebookresearch_esm_main
100%|██████████| 2/2 [00:05<00:00,  2.71s/it]


In [64]:
len(val_dataset), val_dataset[0], val_dataset[0][0].shape

(43,
 (tensor([-0.1717, -0.0072,  0.0006,  ...,  0.0170, -0.0106,  0.1181]),
  array([1.8029228]),
  'MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVNGEWTYDDATKTFTVTE',
  'D40N',
  1),
 torch.Size([1280]))

In [65]:
dataset_path="data/proeng/gb1/two_vs_rest.pkl"
val_dataset = ProtranDataset(dataset_path=dataset_path, 
                             subset="val",
                             encoder_class=ESMEncoder,
                             encoder_name="esm1b_t33_650M_UR50S",
                             embed_layer=0,
                             embed_batch_size=32,
                             flatten_emb="mean",
                             embed_path=None,
                             seq_start_idx = False,
                             seq_end_idx = False,)

0 -1
Loading esm1b_t33_650M_UR50S using 0 layer embedding


Using cache found in /home/t-fli/.cache/torch/hub/facebookresearch_esm_main
100%|██████████| 2/2 [00:29<00:00, 14.74s/it]


In [66]:
len(val_dataset), val_dataset[0], val_dataset[0][0].shape

(43,
 (tensor([-0.1778, -0.0008,  0.0162,  ...,  0.0069,  0.0351,  0.0969]),
  array([1.8029228]),
  'MQYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVNGEWTYDDATKTFTVTELEVLFQGPLDPNSMATYEVLCEVARKLGTDDREVVLFLLNVFIPQPTLAQLIGALRALKEEGRLTFPLLAECLFRAGRRDLLRDLLHLDPRFLERHLAGTMSYFSPYQLTVLHVDGELCARDIRSLIFLSKDTIGSRSTPQTFLHWVYCMENLDLLGPTDVDALMSMLRSLSRVDLQRQVQTLMGLHLSGPSHSQHYRHTPLEHHHHH',
  'D40N',
  1),
 torch.Size([1280]))

In [67]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

In [68]:
from scr.params.train_test import *
from scr.model.pytorch_model import LinearRegression

In [80]:
model = LinearRegression(input_dim=1280, output_dim=1)
model.to(DEVICE)

LinearRegression(
  (linear): Linear(in_features=1280, out_features=1, bias=True)
)

In [85]:
learning_rate = 0.001
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
criterion = nn.MSELoss()
criterion.to(DEVICE, non_blocking=True)

MSELoss()

In [72]:
train_loader = DataLoader(dataset=ProtranDataset(dataset_path=dataset_path, 
                             subset="train",
                             encoder_class=ESMEncoder,
                             encoder_name="esm1b_t33_650M_UR50S",
                             embed_layer=0,
                             embed_batch_size=32,
                             flatten_emb="mean",
                             embed_path=None,
                             seq_start_idx = False,
                             seq_end_idx = 56,),
                             batch_size=64,
                             shuffle=True,
                             worker_init_fn=42)

0 56
Loading esm1b_t33_650M_UR50S using 0 layer embedding


Using cache found in /home/t-fli/.cache/torch/hub/facebookresearch_esm_main
100%|██████████| 12/12 [00:51<00:00,  4.31s/it]


In [82]:
torch.manual_seed(42)
model.train()

for epoch in range(20):
    for (x, y, sequence, mut_name, mut_numb) in train_loader:
        x, y = x.to(DEVICE), y.to(DEVICE)

        optimizer.zero_grad()

        out = model(x)

        loss = criterion(out, y.float())

        loss.backward()

        optimizer.step()

    print(f'train epoch: {epoch}, loss: {loss.item()}')

train epoch: 0, loss: 1.8848106861114502
train epoch: 1, loss: 0.8859107494354248
train epoch: 2, loss: 0.7485132217407227
train epoch: 3, loss: 1.1097514629364014
train epoch: 4, loss: 1.180535912513733
train epoch: 5, loss: 0.9715085029602051
train epoch: 6, loss: 1.5346686840057373
train epoch: 7, loss: 1.1948903799057007
train epoch: 8, loss: 1.3356726169586182
train epoch: 9, loss: 0.8179222941398621
train epoch: 10, loss: 1.529645323753357
train epoch: 11, loss: 0.9965928792953491
train epoch: 12, loss: 1.1581487655639648
train epoch: 13, loss: 0.9006614685058594
train epoch: 14, loss: 1.0335042476654053
train epoch: 15, loss: 0.9751642346382141
train epoch: 16, loss: 0.7143483757972717
train epoch: 17, loss: 1.5195609331130981
train epoch: 18, loss: 1.1130298376083374
train epoch: 19, loss: 1.1967966556549072


In [89]:
len(train_loader.dataset), len(val_loader.dataset)

(381, 43)

In [83]:
train_loader = DataLoader(dataset=ProtranDataset(dataset_path=dataset_path, 
                             subset="train",
                             encoder_class=ESMEncoder,
                             encoder_name="esm1b_t33_650M_UR50S",
                             embed_layer=33,
                             embed_batch_size=32,
                             flatten_emb="mean",
                             embed_path=None,
                             seq_start_idx = False,
                             seq_end_idx = 56,),
                             batch_size=64,
                             shuffle=True,
                             worker_init_fn=42)

0 56
Loading esm1b_t33_650M_UR50S using 33 layer embedding


Using cache found in /home/t-fli/.cache/torch/hub/facebookresearch_esm_main
100%|██████████| 12/12 [00:53<00:00,  4.43s/it]


In [86]:
torch.manual_seed(42)
model.train()

for epoch in range(20):
    for (x, y, sequence, mut_name, mut_numb) in train_loader:
        x, y = x.to(DEVICE), y.to(DEVICE)

        optimizer.zero_grad()

        out = model(x)

        loss = criterion(out, y.float())

        loss.backward()

        optimizer.step()

    print(f'train epoch: {epoch}, loss: {loss.item()}')

train epoch: 0, loss: 1.0062204599380493
train epoch: 1, loss: 0.860078752040863
train epoch: 2, loss: 0.626774787902832
train epoch: 3, loss: 1.0024996995925903
train epoch: 4, loss: 1.1956404447555542
train epoch: 5, loss: 0.903653085231781
train epoch: 6, loss: 1.43190336227417
train epoch: 7, loss: 1.1046732664108276
train epoch: 8, loss: 1.2266196012496948
train epoch: 9, loss: 0.7690103650093079
train epoch: 10, loss: 1.4974141120910645
train epoch: 11, loss: 0.9335665106773376
train epoch: 12, loss: 1.0518162250518799
train epoch: 13, loss: 0.8178434371948242
train epoch: 14, loss: 0.946225106716156
train epoch: 15, loss: 0.9004098773002625
train epoch: 16, loss: 0.6763227581977844
train epoch: 17, loss: 1.3393670320510864
train epoch: 18, loss: 0.9797210097312927
train epoch: 19, loss: 1.0611830949783325
