In [1]:
%cd ~/repo/protein-transfer

/home/t-fli/repo/protein-transfer


In [2]:
%load_ext blackcellmagic

In [3]:
import os
import numpy as np
import pandas as pd

In [35]:
df = pd.read_csv("data/structure/secondary_structure/tape_ss3.csv")
df.head()

sequence  \
0  AETVESCLAKSHTENSFTNVXKDDKTLDRYANYEGCLWNATGVVVC...   
1  ASQEISKSIYTCNDNQVXEVIYVNTEAGNAYAIISQVNEXIPXRLX...   
2  XGSSHHHHHHSSGRENLYFQGXNISEINGFEVTGFVVRTTNADEXN...   
3  SNADYNRLSVPGNVIGKGGNAVVYEDAEDATKVLKMFTTSQSNEEV...   
4  DTVGRPLPHLAAAMQASGEAVYCDDIPRYENELFLRLVTSTRAHAK...   

                                                 ss3  split  
0  [2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, ...  train  
1  [2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, ...  train  
2  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...  train  
3  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, ...  train  
4  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, ...  train

In [5]:
from sklearn.datasets import make_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import shuffle
import numpy as np

X, y1 = make_classification(n_samples=10, n_features=100,
                            n_informative=30, n_classes=3,
                            random_state=1)
y2 = shuffle(y1, random_state=1)
y3 = shuffle(y1, random_state=2)
Y = np.vstack((y1, y2, y3)).T
n_samples, n_features = X.shape # 10,100
n_outputs = Y.shape[1] # 3
n_classes = 3
forest = RandomForestClassifier(random_state=1)
multi_target_forest = MultiOutputClassifier(forest, n_jobs=2)
multi_target_forest.fit(X, Y).predict(X)

array([[2, 2, 0],
       [1, 2, 1],
       [2, 1, 0],
       [0, 0, 2],
       [0, 2, 1],
       [0, 0, 2],
       [1, 1, 0],
       [1, 1, 1],
       [0, 0, 2],
       [2, 0, 0]])

In [12]:
X.shape, Y.shape, y1.shape

((10, 100), (10, 3), (10,))

In [16]:
X, y1 = make_classification(n_samples=10, n_features=100,
                            n_informative=30, n_classes=3,
                            random_state=1)
ys = [shuffle(y1, random_state=i) for i in range(99)]
Y = np.vstack((y1, ys)).T
print(Y.shape)
n_samples, n_features = X.shape # 10,100
n_outputs = Y.shape[1] # 3
n_classes = 3
forest = RandomForestClassifier(random_state=1)
multi_target_forest = MultiOutputClassifier(forest, n_jobs=2)
Y_pred = multi_target_forest.fit(X, Y).predict(X)

(10, 100)


In [17]:
X.shape, Y.shape, y1.shape, Y_pred.shape

((10, 100), (10, 100), (10,), (10, 100))

In [13]:
from scr.encoding.encoding_classes import ESMEncoder

In [14]:
mean_batch_encoder = ESMEncoder(
    encoder_name="esm1_t6_43M_UR50S",
).encode(mut_seqs=list(df.sequence), batch_size=64, flatten_emb=False)
one_mean_emb = next(mean_batch_encoder)
one_mean_emb[0].shape

Generating esm1_t6_43M_UR50S upto 6 layer embedding ...


Using cache found in /home/t-fli/.cache/torch/hub/facebookresearch_esm_main
  0%|          | 0/180 [00:00<?, ?it/s]

(64, 756, 768)

In [90]:
X = one_mean_emb[0]
X.shape

(64, 756, 768)

In [36]:
np_y = df["ss3"].apply(lambda x: np.array(x[1:-1].split(", ")).astype("int")) + 1
max_len = max(len(y) for y in np_y)
print("print np_y shape for dataset")
ss3_y = np.stack([np.pad(i, pad_width=(0, max_len - len(i)), constant_values=0,) for i in np_y])
ss3_y, ss3_y.shape

print np_y shape for dataset


(array([[3, 3, 3, ..., 0, 0, 0],
        [3, 3, 3, ..., 0, 0, 0],
        [3, 3, 3, ..., 0, 0, 0],
        ...,
        [3, 2, 2, ..., 0, 0, 0],
        [3, 3, 3, ..., 0, 0, 0],
        [3, 3, 2, ..., 0, 0, 0]]),
 (11497, 1632))

In [37]:
ss3_y[:64]

array([[3, 3, 3, ..., 0, 0, 0],
       [3, 3, 3, ..., 0, 0, 0],
       [3, 3, 3, ..., 0, 0, 0],
       ...,
       [3, 3, 3, ..., 0, 0, 0],
       [3, 3, 2, ..., 0, 0, 0],
       [3, 3, 3, ..., 0, 0, 0]])

In [ ]:
(np.arange(ss3_y[:64].max()+1) == ss3_y[:64][...,None]).astype(int)

In [46]:
(np.arange(ss3_y[:64].max()+1) == ss3_y[:64][...,None]).astype(int), (np.arange(ss3_y[:64].max()+1) == ss3_y[:64][...,None]).astype(int).shape

(array([[[0, 0, 0, 1],
         [0, 0, 0, 1],
         [0, 0, 0, 1],
         ...,
         [1, 0, 0, 0],
         [1, 0, 0, 0],
         [1, 0, 0, 0]],
 
        [[0, 0, 0, 1],
         [0, 0, 0, 1],
         [0, 0, 0, 1],
         ...,
         [1, 0, 0, 0],
         [1, 0, 0, 0],
         [1, 0, 0, 0]],
 
        [[0, 0, 0, 1],
         [0, 0, 0, 1],
         [0, 0, 0, 1],
         ...,
         [1, 0, 0, 0],
         [1, 0, 0, 0],
         [1, 0, 0, 0]],
 
        ...,
 
        [[0, 0, 0, 1],
         [0, 0, 0, 1],
         [0, 0, 0, 1],
         ...,
         [1, 0, 0, 0],
         [1, 0, 0, 0],
         [1, 0, 0, 0]],
 
        [[0, 0, 0, 1],
         [0, 0, 0, 1],
         [0, 0, 1, 0],
         ...,
         [1, 0, 0, 0],
         [1, 0, 0, 0],
         [1, 0, 0, 0]],
 
        [[0, 0, 0, 1],
         [0, 0, 0, 1],
         [0, 0, 0, 1],
         ...,
         [1, 0, 0, 0],
         [1, 0, 0, 0],
         [1, 0, 0, 0]]]),
 (64, 1632, 4))

In [40]:
ss3_oh_y = OneHotEncoder().fit_transform(ss3_y[:64]).toarray()
ss3_oh_y.shape

(64, 3486)

In [41]:
ss3_oh_y

array([[1., 0., 0., ..., 1., 1., 1.],
       [1., 0., 0., ..., 1., 1., 1.],
       [1., 0., 0., ..., 1., 1., 1.],
       ...,
       [1., 0., 0., ..., 1., 1., 1.],
       [1., 0., 0., ..., 1., 1., 1.],
       [1., 0., 0., ..., 1., 1., 1.]])

In [42]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()

In [43]:
lb.transform(ss3_y[:64])

NotFittedError: This LabelBinarizer instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [50]:
class MultiLabelMultiClass(nn.Module):
    """Multi label multi class"""

    def __init__(self, input_dim: int, numb_class: int) -> None:
        super(MultiLabelMultiClass, self).__init__()
        self.linear = nn.Linear(input_dim, numb_class)
        self.softmax = nn.Softmax(dim=2)


    def forward(self, x: torch.tensor) -> torch.tensor:
        print("multilabel output inside forward")
        # print(self.softmax(self.linear(x)).shape)
        # return self.softmax(self.linear(x))
        print(self.softmax(self.linear(x)), )
        return self.softmax(self.linear(x))

    @property
    def model_name(self) -> str:
        """Return the name of the model"""
        return "MultiLabelMultiClass"

In [15]:
m = nn.Linear(768, 4)
y = m(torch.from_numpy(one_mean_emb[0]))
y, y.shape

(tensor([[[ 2.8619e-01,  3.0612e-01,  6.2143e-01,  8.3901e-01],
          [ 3.3634e-01,  3.6491e-01,  5.6606e-01,  9.6666e-01],
          [ 2.6897e-01,  1.8964e-01,  6.1311e-01,  8.9628e-01],
          ...,
          [-5.0892e-03, -3.3327e-02, -2.2007e-02,  1.2481e-02],
          [-5.0892e-03, -3.3327e-02, -2.2007e-02,  1.2481e-02],
          [-5.0892e-03, -3.3327e-02, -2.2007e-02,  1.2481e-02]],
 
         [[ 2.8619e-01,  3.0612e-01,  6.2143e-01,  8.3901e-01],
          [ 4.9324e-02,  2.6449e-01,  6.4939e-01,  7.8951e-01],
          [ 2.8519e-01,  2.9909e-01,  4.2499e-01,  1.1066e+00],
          ...,
          [-5.0892e-03, -3.3327e-02, -2.2007e-02,  1.2481e-02],
          [-5.0892e-03, -3.3327e-02, -2.2007e-02,  1.2481e-02],
          [-5.0892e-03, -3.3327e-02, -2.2007e-02,  1.2481e-02]],
 
         [[ 2.5869e-01,  5.3333e-01,  5.1984e-01,  6.6602e-01],
          [ 2.1767e-01,  3.6173e-01,  7.1477e-01,  8.3051e-01],
          [-2.3775e-03,  1.5438e-01,  6.6957e-01,  8.6444e-01],
    

In [28]:
nn.Softmax()(y)

/tmp/ipykernel_1357099/2949005056.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  nn.Softmax()(y)


tensor([[[0.0159, 0.0147, 0.0166, 0.0163],
         [0.0180, 0.0180, 0.0152, 0.0175],
         [0.0183, 0.0168, 0.0160, 0.0153],
         ...,
         [0.0155, 0.0155, 0.0157, 0.0156],
         [0.0157, 0.0155, 0.0158, 0.0156],
         [0.0156, 0.0154, 0.0157, 0.0157]],

        [[0.0159, 0.0147, 0.0166, 0.0163],
         [0.0135, 0.0162, 0.0165, 0.0146],
         [0.0186, 0.0188, 0.0133, 0.0189],
         ...,
         [0.0155, 0.0155, 0.0157, 0.0156],
         [0.0157, 0.0155, 0.0158, 0.0156],
         [0.0156, 0.0154, 0.0157, 0.0157]],

        [[0.0155, 0.0184, 0.0150, 0.0137],
         [0.0160, 0.0179, 0.0176, 0.0153],
         [0.0140, 0.0162, 0.0170, 0.0148],
         ...,
         [0.0155, 0.0155, 0.0157, 0.0156],
         [0.0157, 0.0155, 0.0158, 0.0156],
         [0.0156, 0.0154, 0.0157, 0.0157]],

        ...,

        [[0.0160, 0.0151, 0.0150, 0.0153],
         [0.0135, 0.0162, 0.0165, 0.0146],
         [0.0170, 0.0133, 0.0144, 0.0140],
         ...,
         [0.0155, 0.0

In [16]:
y.softmax(-1)

tensor([[[0.1939, 0.1978, 0.2712, 0.3371],
         [0.1936, 0.1992, 0.2436, 0.3636],
         [0.1920, 0.1774, 0.2709, 0.3596],
         ...,
         [0.2517, 0.2447, 0.2475, 0.2562],
         [0.2517, 0.2447, 0.2475, 0.2562],
         [0.2517, 0.2447, 0.2475, 0.2562]],

        [[0.1939, 0.1978, 0.2712, 0.3371],
         [0.1624, 0.2014, 0.2959, 0.3404],
         [0.1839, 0.1865, 0.2115, 0.4181],
         ...,
         [0.2517, 0.2447, 0.2475, 0.2562],
         [0.2517, 0.2447, 0.2475, 0.2562],
         [0.2517, 0.2447, 0.2475, 0.2562]],

        [[0.1954, 0.2572, 0.2537, 0.2937],
         [0.1772, 0.2046, 0.2912, 0.3270],
         [0.1537, 0.1798, 0.3009, 0.3657],
         ...,
         [0.2517, 0.2447, 0.2475, 0.2562],
         [0.2517, 0.2447, 0.2475, 0.2562],
         [0.2517, 0.2447, 0.2475, 0.2562]],

        ...,

        [[0.2028, 0.2120, 0.2550, 0.3302],
         [0.1624, 0.2014, 0.2959, 0.3404],
         [0.2002, 0.1576, 0.2736, 0.3686],
         ...,
         [0.2517, 0.2

In [27]:
nn.LogSoftmax(dim=2)(y)

tensor([[[-1.6403, -1.6203, -1.3050, -1.0874],
         [-1.6420, -1.6134, -1.4123, -1.0117],
         [-1.6500, -1.7293, -1.3059, -1.0227],
         ...,
         [-1.3795, -1.4078, -1.3965, -1.3620],
         [-1.3795, -1.4078, -1.3965, -1.3620],
         [-1.3795, -1.4078, -1.3965, -1.3620]],

        [[-1.6403, -1.6203, -1.3050, -1.0874],
         [-1.8179, -1.6027, -1.2178, -1.0777],
         [-1.6934, -1.6795, -1.5536, -0.8719],
         ...,
         [-1.3795, -1.4078, -1.3965, -1.3620],
         [-1.3795, -1.4078, -1.3965, -1.3620],
         [-1.3795, -1.4078, -1.3965, -1.3620]],

        [[-1.6326, -1.3580, -1.3715, -1.2253],
         [-1.7307, -1.5866, -1.2336, -1.1179],
         [-1.8729, -1.7161, -1.2009, -1.0061],
         ...,
         [-1.3795, -1.4078, -1.3965, -1.3620],
         [-1.3795, -1.4078, -1.3965, -1.3620],
         [-1.3795, -1.4078, -1.3965, -1.3620]],

        ...,

        [[-1.5953, -1.5511, -1.3666, -1.1081],
         [-1.8179, -1.6027, -1.2178, -1.0777]

In [96]:
torch.argmax(y, dim=2), torch.argmax(y, dim=2).shape, 

(tensor([[1, 1, 1,  ..., 3, 3, 3],
         [1, 1, 1,  ..., 3, 3, 3],
         [1, 1, 1,  ..., 3, 3, 3],
         ...,
         [1, 1, 1,  ..., 3, 3, 3],
         [1, 1, 1,  ..., 3, 3, 3],
         [1, 1, 1,  ..., 3, 3, 3]]),
 torch.Size([64, 756]))

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [101]:
torch.argmax(y, dim=2)[2]

tensor([1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 2,
        2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1,
        3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 2, 3, 1, 1, 1, 1,
        1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 1, 1, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [78]:
0.2810 + 0.2385 + 0.2313 + 0.2058

0.9566000000000001

In [80]:
0.2432 + 0.2856 + 0.1944 + 0.2473

0.9705

In [93]:
0.1000 + 0.4497 + 0.1851 + 0.2651

0.9998999999999999

In [94]:
sm = nn.Softmax(dim=0)
y_cls = sm(y)
y_cls, y_cls.shape

(tensor([[[0.0137, 0.0172, 0.0139, 0.0154],
          [0.0192, 0.0170, 0.0148, 0.0139],
          [0.0146, 0.0171, 0.0145, 0.0147],
          ...,
          [0.0156, 0.0156, 0.0156, 0.0154],
          [0.0156, 0.0157, 0.0156, 0.0154],
          [0.0156, 0.0157, 0.0157, 0.0154]],
 
         [[0.0137, 0.0172, 0.0139, 0.0154],
          [0.0141, 0.0167, 0.0177, 0.0171],
          [0.0173, 0.0154, 0.0152, 0.0145],
          ...,
          [0.0156, 0.0156, 0.0156, 0.0154],
          [0.0156, 0.0157, 0.0156, 0.0154],
          [0.0156, 0.0157, 0.0157, 0.0154]],
 
         [[0.0228, 0.0119, 0.0158, 0.0107],
          [0.0160, 0.0123, 0.0171, 0.0159],
          [0.0139, 0.0174, 0.0176, 0.0180],
          ...,
          [0.0156, 0.0156, 0.0156, 0.0154],
          [0.0156, 0.0157, 0.0156, 0.0154],
          [0.0156, 0.0157, 0.0157, 0.0154]],
 
         ...,
 
         [[0.0170, 0.0178, 0.0143, 0.0183],
          [0.0141, 0.0167, 0.0177, 0.0171],
          [0.0178, 0.0145, 0.0167, 0.0168],
      

In [13]:
df.ss3[:4]

0    [2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, ...
1    [2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, ...
2    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
3    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, ...
Name: ss3, dtype: object

In [14]:
Y = df.ss3[:4].to_numpy()
Y.shape

(4,)

In [15]:
Y

array([array(['2', '2', '2', '0', '0', '0', '0', '0', '2', '2', '2', '2', '1',
              '1', '1', '1', '1', '1', '2', '2', '1', '1', '2', '2', '2', '2',
              '2', '2', '1', '1', '1', '1', '1', '2', '2', '1', '1', '1', '1',
              '1', '1', '1', '1', '1', '1', '1', '2', '2', '2', '2', '2', '1',
              '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '2', '2', '2',
              '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2',
              '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2',
              '2', '2', '2', '2', '2', '1', '1', '1', '1', '1', '2', '2', '2',
              '2', '2', '2', '2', '2', '2', '2', '1', '2', '2', '2', '2', '1',
              '2', '2', '2', '2', '2', '2', '1', '1', '1', '2', '2', '2', '2',
              '2', '2', '2', '1', '1', '1', '2', '2', '1', '1', '1', '1', '1',
              '1', '2', '2', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
              '1', '2', '2', '2', '2', '2', '1', '1'

In [21]:
X.shape[1]

217

In [22]:
np.stack([np.pad(y, pad_width=(0, X.shape[1] - len(y)), constant_values=-1) for y in Y])

array([['2', '2', '2', '0', '0', '0', '0', '0', '2', '2', '2', '2', '1',
        '1', '1', '1', '1', '1', '2', '2', '1', '1', '2', '2', '2', '2',
        '2', '2', '1', '1', '1', '1', '1', '2', '2', '1', '1', '1', '1',
        '1', '1', '1', '1', '1', '1', '1', '2', '2', '2', '2', '2', '1',
        '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '2', '2', '2',
        '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2',
        '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2',
        '2', '2', '2', '2', '2', '1', '1', '1', '1', '1', '2', '2', '2',
        '2', '2', '2', '2', '2', '2', '2', '1', '2', '2', '2', '2', '1',
        '2', '2', '2', '2', '2', '2', '1', '1', '1', '2', '2', '2', '2',
        '2', '2', '2', '1', '1', '1', '2', '2', '1', '1', '1', '1', '1',
        '1', '2', '2', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
        '1', '2', '2', '2', '2', '2', '1', '1', '1', '1', '1', '1', '1',
        '1', '2', '2', '2', '0', '0', '0', '0', '0'

In [ ]:
# pad wiht -1
np.pad(y, pad_width=((0, X.shape[1] - len(y)), (-1 , -1)))

In [21]:
"""Pre-processing the dataset"""

from __future__ import annotations

from collections import defaultdict

import os
from glob import glob
import tables
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

import torch
from torch.utils.data import Dataset, DataLoader

from scr.utils import pickle_save, pickle_load, replace_ext
from scr.params.sys import RAND_SEED
from scr.params.emb import TRANSFORMER_INFO, CARP_INFO, MAX_SEQ_LEN
from scr.preprocess.seq_loader import SeqLoader
from scr.encoding.encoding_classes import (
    AbstractEncoder,
    ESMEncoder,
    CARPEncoder,
    OnehotEncoder,
)


def get_mut_name(mut_seq: str, parent_seq: str) -> str:
    """
    A function for returning the mutant name

    Args:
    - mut_seq: str, the full mutant sequence
    - parent_seq: str, the full parent sequence

    Returns:
    - str, parent, indel, or mutant name in the format of
        ParentAAMutLocMutAA:ParentAAMutLocMutAA:..., ie. W39W:D40G:G41C:V54Q
    """

    mut_list = []
    if parent_seq == mut_seq:
        return "parent"
    elif len(parent_seq) == len(mut_seq):
        for i, (p, m) in enumerate(zip(list(parent_seq), list(mut_seq))):
            if p != m:
                mut_list.append(f"{p}{i+1}{m}")
        return ":".join(mut_list)
    else:
        return "indel"


class AddMutInfo:
    """A class for appending mutation info for mainly protein engineering tasks"""

    def __init__(self, parent_seq_path: str, csv_path: str):

        """
        Args:
        - parent_seq_path: str, path for the parent sequence
        - csv_path: str, path for the fitness csv file
        """

        # Load the parent sequence from the fasta file
        self._parent_seq = SeqLoader(parent_seq_path=parent_seq_path)

        # load the dataframe
        self._init_df = pd.read_csv(csv_path)

        self._df = self._init_df.copy()
        # add a column with the mutant names
        self._df["mut_name"] = self._init_df["sequence"].apply(
            get_mut_name, parent_seq=self._parent_seq
        )
        # add a column with the number of mutations
        self._df["mut_numb"] = (
            self._df["mut_name"].str.split(":").map(len, na_action="ignore")
        )

        # get the pickle file path
        self._pkl_path = replace_ext(input_path=csv_path, ext=".pkl")

        pickle_save(what2save=self._df, where2save=self._pkl_path)

    @property
    def parent_seq(self) -> str:
        """Return the parent sequence"""
        return self._parent_seq

    @property
    def pkl_path(self) -> str:
        """Return the pkl file path for the processed dataframe"""
        return self._pkl_path

    @property
    def df(self) -> pd.DataFrame:
        """Return the processed dataframe"""
        return self._df


def std_ssdf(
    ssdf_path: str = "data/structure/secondary_structure/tape_ss3.csv",
) -> None:
    """
    A function that standardize secondary structure dataset
    to set up as columns as sequence, target, set, validation
    where set is train or test and add validation as true
    """
    folder_path = os.path.dirname(ssdf_path)

    df = pd.read_csv(ssdf_path)

    # convert the string into numpy array
    # df["ss3"] = df["ss3"].apply(lambda x: np.array(x[1:-1].split(", ")))

    # add validation column
    df["validation"] = df["split"].apply(lambda x: True if x == "valid" else "")
    # now replace valid to train
    df = df.replace("valid", "train")
    # rename all columns
    df.columns = ["sequence", "target", "set", "validation"]

    # get all kinds of test sets
    ss_tests = set(df["set"].unique()) - set(["train"])

    for ss_test in ss_tests:
        df.loc[~df["set"].isin(set(ss_tests) - set([ss_test]))].replace(
            ss_test, "test"
        ).to_csv(os.path.join(folder_path, ss_test + ".csv"), index=False)


def split_train_val_test_df(df: pd.DataFrame) -> list[pd.DataFrame]:
    """
    Return split dataframe for training, validation, and testing

    Args:
    - df: pd.DataFrame, input dataframe

    Returns:
    - a list of dataframes for train, val, test
    """
    return (
        df.loc[(df["set"] == "train") & (df["validation"] != True)],
        df.loc[(df["set"] == "train") & (df["validation"] == True)],
        df.loc[(df["set"] == "test")],
    )


class DatasetInfo:
    """
    A class returns the information of a dataset
    """

    def __init__(self, dataset_path: str) -> None:
        """
        Args:
        - dataset_path: str, the path for the csv
        """
        self._df = pd.read_csv(dataset_path)

    def get_model_type(self) -> str:
        # pick linear regression if y numerical
        if self._df.target.dtype.kind in "iufc":
            return "LinearRegression"
        else:
            # ss3
            if "[" in self._df.target[0]:
                return "MultiLabelMultiClass"
            # annotation
            else:
                return "LinearClassifier"

    def get_numb_class(self) -> int:
        """
        A function to get number of class
        """
        # annotation class number
        if self.model_type == "LinearClassifier":
            return self._df.target.nunique()
        # ss3 or ss8 secondary structure states plus padding
        elif self.model_type == "MultiLabelMultiClass":
            return len(np.unique(np.array(self._df["target"][0][1:-1].split(", ")))) + 1

    @property
    def model_type(self) -> str:
        """Return the pytorch model type"""
        return self.get_model_type()

    @property
    def numb_class(self) -> int:
        """Return number of classes for classification"""
        return self.get_numb_class()


class TaskProcess:
    """A class for handling different downstream tasks"""

    def __init__(self, data_folder: str = "data/"):
        """
        Args:
        - data_folder: str, a folder path with all the tasks as subfolders where
            all the subfolders have datasets as the subsubfolders, ie

            {data_folder}/
                proeng/
                    aav/
                        one_vs_many.csv
                        two_vs_many.csv
                        P03135.fasta
                    thermo/
                        mixed.csv
        """

        if data_folder[-1] == "/":
            self._data_folder = data_folder
        else:
            self._data_folder = data_folder + "/"

        # sumamarize all files i nthe data folder
        self._sum_file_df = self.sum_files()

    def sum_files(self) -> pd.DataFrame:
        """
        Summarize all files in the data folder

        Returns:
        - A dataframe with "task", "dataset", "split",
            "csv_path", "fasta_path", "pkl_path" as columns, ie.
            (proeng, gb1, low_vs_high, data/proeng/gb1/low_vs_high.csv,
            data/proeng/gb1/5LDE_1.fasta)
            note that csv_path is the list of lmdb files for the structure task
        """
        dataset_folders = glob(f"{self._data_folder}*/*")
        # need a list of tuples in the order of:
        # (task, dataset, split, csv_path, fasta_path)
        list_for_df = []
        for dataset_folder in dataset_folders:
            _, task, dataset = dataset_folder.split("/")

            csv_paths = glob(f"{dataset_folder}/*.csv")

            if task == "structure":
                csv_paths = set(csv_paths) - set(glob(f"{dataset_folder}/tape_ss3.csv"))

            fasta_paths = glob(f"{dataset_folder}/*.fasta")
            pkl_paths = glob(f"{dataset_folder}/*.pkl")

            assert len(csv_paths) >= 1, "Less than one csv"
            assert len(fasta_paths) <= 1, "More than one fasta"

            for csv_path in csv_paths:
                # if parent seq fasta exists
                if len(fasta_paths) == 1:
                    fasta_path = fasta_paths[0]

                    # if no existing pkl file, generate and save
                    if len(pkl_paths) == 0:
                        print(f"Adding mutation info to {csv_path}...")
                        pkl_path = AddMutInfo(
                            parent_seq_path=fasta_path, csv_path=csv_path
                        ).pkl_path
                    # pkl file exits
                    else:
                        pkl_path = replace_ext(input_path=csv_path, ext=".pkl")
                # no parent fasta no pkl file
                else:
                    fasta_path = ""
                    pkl_path = ""

                train_df, val_df, test_df = split_train_val_test_df(
                    pd.read_csv(csv_path)
                )

                list_for_df.append(
                    tuple(
                        [
                            task,
                            dataset,
                            os.path.basename(os.path.splitext(csv_path)[0]),
                            len(train_df),
                            len(val_df),
                            len(test_df),
                            csv_path,
                            fasta_path,
                            pkl_path,
                        ]
                    )
                )

        return pd.DataFrame(
            list_for_df,
            columns=[
                "task",
                "dataset",
                "split",
                "train_numb",
                "val_numb",
                "test_numb",
                "csv_path",
                "fasta_path",
                "pkl_path",
            ],
        )

    @property
    def sum_file_df(self) -> pd.DataFrame:
        """A summary table for all files in the data folder"""
        return self._sum_file_df


class ProtranDataset(Dataset):

    """A dataset class for processing protein transfer data"""

    def __init__(
        self,
        dataset_path: str,
        subset: str,
        encoder_name: str,
        reset_param: bool = False,
        resample_param: bool = False,
        embed_batch_size: int = 0,
        flatten_emb: bool | str = False,
        embed_folder: str = None,
        embed_layer: int | None = None,
        seq_start_idx: bool | int = False,
        seq_end_idx: bool | int = False,
        if_encode_all: bool = True,
        **encoder_params,
    ):

        """
        Args:
        - dataset_path: str, full path to the dataset, in pkl or panda readable format, ie
            "data/proeng/gb1/low_vs_high.csv"
            columns include: sequence, target, set, validation,
            mut_name (optional), mut_numb (optional)
        - subset: str, train, val, test
        - encoder_name: str, the name of the encoder
        - reset_param: bool = False, if update the full model to xavier_uniform_
        - resample_param: bool = False, if update the full model to xavier_normal_
        - embed_batch_size: int, set to 0 to encode all in a single batch
        - flatten_emb: bool or str, if and how (one of ["max", "mean"]) to flatten the embedding
        - embed_folder: str = None, path to presaved embedding folder, ie
            "embeddings/proeng/gb1/low_vs_high"
            for which then can add the subset to be, ie
            "embeddings/proeng/gb1/low_vs_high/esm1_t6_43M_UR50S/mean/test/embedding.h5"
        - seq_start_idx: bool | int = False, the index for the start of the sequence
        - seq_end_idx: bool | int = False, the index for the end of the sequence
        - if_encode_all: bool = True, if encode full dataset all layers on the fly
        - encoder_params: kwarg, additional parameters for encoding
        """

        # with additional info mut_name, mut_numb
        if os.path.splitext(dataset_path)[-1] in [".pkl", ".PKL", ""]:
            self._df = pickle_load(dataset_path)
            self._add_mut_info = True
        # without such info
        else:
            self._df = pd.read_csv(dataset_path)
            self._ds_info = DatasetInfo(dataset_path)
            self._model_type = self._ds_info.model_type
            self._numb_class = self._ds_info.numb_class

            self._add_mut_info = False

        assert "set" in self._df.columns, f"set is not a column in {dataset_path}"
        assert (
            "validation" in self._df.columns
        ), f"validation is not a column in {dataset_path}"

        """
        self._df_train = self._df.loc[
            (self._df["set"] == "train") & (self._df["validation"] != True)
        ]
        self._df_val = self._df.loc[
            (self._df["set"] == "train") & (self._df["validation"] == True)
        ]
        self._df_test = self._df.loc[(self._df["set"] == "test")]
        """

        self._df_train, self._df_val, self._df_test = split_train_val_test_df(self._df)

        self._df_dict = {
            "train": self._df_train,
            "val": self._df_val,
            "test": self._df_test,
        }

        assert subset in list(
            self._df_dict.keys()
        ), "split can only be 'train', 'val', or 'test'"
        self._subset = subset

        self._subdf_len = len(self._df_dict[self._subset])

        # not specified seq start will be from 0
        if seq_start_idx == False:
            self._seq_start_idx = 0
        else:
            self._seq_start_idx = int(seq_start_idx)
        # not specified seq end will be the full sequence length
        if seq_end_idx == False:
            self._seq_end_idx = -1
            self._max_seq_len = self._df.sequence.str.len().max()
        else:
            self._seq_end_idx = int(seq_end_idx)
            self._max_seq_len = self._seq_end_idx - self._seq_start_idx

        # get unencoded string of input sequence
        # will need to convert data type
        self.sequence = self._get_column_value("sequence")

        self.if_encode_all = if_encode_all
        self._embed_folder = embed_folder

        self._encoder_name = encoder_name
        self._flatten_emb = flatten_emb

        # get the encoder class
        if self._encoder_name in TRANSFORMER_INFO.keys():
            encoder_class = ESMEncoder
        elif self._encoder_name in CARP_INFO.keys():
            encoder_class = CARPEncoder
        else:
            encoder_class = OnehotEncoder
            encoder_params["max_seq_len"] = self._max_seq_len

        # get the encoder
        self._encoder = encoder_class(
            encoder_name=self._encoder_name,
            reset_param=reset_param,
            resample_param=resample_param,
            **encoder_params,
        )
        self._total_emb_layer = self._encoder.total_emb_layer
        self._embed_layer = embed_layer

        # encode all and load in memory
        if self.if_encode_all or (
            self._embed_folder is None and self._embed_layer is None
        ):
            print("Encoding all...")
            # encode the sequences without the mut_name
            # init an empty dict with empty list to append emb
            encoded_dict = defaultdict(list)

            # use the encoder generator for batch emb
            # assume no labels included
            for encoded_batch_dict in self._encoder.encode(
                mut_seqs=self.sequence,
                batch_size=embed_batch_size,
                flatten_emb=self._flatten_emb,
            ):

                for layer, emb in encoded_batch_dict.items():
                    encoded_dict[layer].append(emb)

            # assign each layer as its own variable
            for layer, emb in encoded_dict.items():
                setattr(self, "layer" + str(layer), np.vstack(emb))

        # load full one layer embedding
        if self._embed_folder is not None and self._embed_layer is not None:

            emb_table = tables.open_file(
                os.path.join(
                    self._embed_folder,
                    self._encoder_name,
                    self._flatten_emb,
                    self._subset,
                    "embedding.h5",
                )
            )

            emb_table.flush()

            print(f"setting attr for layer {self._embed_layer}")

            setattr(
                self,
                "layer" + str(self._embed_layer),
                getattr(emb_table.root, "layer" + str(self._embed_layer))[:],
            )

            emb_table.close()
        # get and format the fitness or secondary structure values
        # can be numbers or string
        # will need to convert data type
        # make 1D tensor 2D
        self.y = np.expand_dims(self._get_column_value("target"), 1)

        # add mut_name and mut_numb for relevant proeng datasets
        if self._add_mut_info:
            self.mut_name = self._get_column_value("mut_name")
            self.mut_numb = self._get_column_value("mut_numb")
        else:
            self.mut_name = [""] * self._subdf_len
            self.mut_numb = [np.nan] * self._subdf_len

    def __len__(self):
        """Return the length of the selected subset of the dataframe"""
        return self._subdf_len

    def __getitem__(self, idx: int):

        """
        Return the item in the order of
        target (y), sequence, mut_name (optional), mut_numb (optional),
        embedding per layer upto the max number of layer for the encoder

        Args:
        - idx: int
        """
        if self.if_encode_all and self._embed_folder is None:

            return (
                self.y[idx],
                self.sequence[idx],
                self.mut_name[idx],
                self.mut_numb[idx],
                *(
                    getattr(self, "layer" + str(layer))[idx]
                    for layer in range(self._total_emb_layer)
                ),
            )
        elif self._embed_folder is not None:
            # load the .h5 file with the embeddings
            """
            gb1_emb = tables.open_file("embeddings/proeng/gb1/low_vs_high/esm1_t6_43M_UR50S/mean/test/embedding.h5")
            gb1_emb.flush()
            gb1_emb.root.layer0[0:5]
            """
            # return all
            if self._embed_layer is None:

                emb_table = tables.open_file(
                    os.path.join(
                        self._embed_folder,
                        self._encoder_name,
                        self._flatten_emb,
                        self._subset,
                        "embedding.h5",
                    )
                )

                emb_table.flush()

                layer_embs = [
                    getattr(emb_table.root, "layer" + str(layer))[idx]
                    for layer in range(self._total_emb_layer)
                ]

                emb_table.close()

                return (
                    self.y[idx],
                    self.sequence[idx],
                    self.mut_name[idx],
                    self.mut_numb[idx],
                    layer_embs,
                )
            # only pick particular embeding layer
            else:
                """
                setattr(
                    self,
                    "layer" + str(self._embed_layer),
                    getattr(emb_table.root, "layer" + str(self._embed_layer)),
                )"""

                return (
                    self.y[idx],
                    self.sequence[idx],
                    self.mut_name[idx],
                    self.mut_numb[idx],
                    # getattr(emb_table.root, "layer" + str(self._embed_layer))[idx]
                    getattr(self, "layer" + str(self._embed_layer))[idx],
                )
        else:
            return (
                self.y[idx],
                self.sequence[idx],
                self.mut_name[idx],
                self.mut_numb[idx],
            )

    def _get_column_value(self, column_name: str) -> np.ndarray:
        """
        Check and return the column values of the selected dataframe subset

        Args:
        - column_name: str, the name of the dataframe column
        """
        if column_name in self._df.columns:
            y = self._df_dict[self._subset][column_name]

            if column_name == "sequence":

                return (
                    # self._df_dict[self._subset]["sequence"]
                    y.astype(str)
                    .str[self._seq_start_idx : self._seq_end_idx]
                    .apply(
                        lambda x: x[: int(MAX_SEQ_LEN // 2)]
                        + x[-int(MAX_SEQ_LEN // 2) :]
                        if len(x) > MAX_SEQ_LEN
                        else x
                    )
                    .values
                )
            elif column_name == "target" and self._model_type == "LinearClassifier":
                print("Converting classes into int...")
                le = LabelEncoder()
                return le.fit_transform(y.values.flatten())
            elif column_name == "target" and self._model_type == "MultiLabelMultiClass":
                print("Converting ss3/ss8 into np.array...")
       
                np_y = y.apply(lambda x: np.array(x[1:-1].split(", ")).astype("int")) + 1
                max_len = max(len(y) for y in np_y)
                print("print np_y shape for dataset")
                print(np.stack([np.pad(i, pad_width=(0, max_len - len(i)), constant_values=0,) for i in np_y]).shape)
                return np.stack([np.pad(i, pad_width=(0, max_len - len(i)), constant_values=0,) for i in np_y])
            else:
                return y.values

    @property
    def df_full(self) -> pd.DataFrame:
        """Return the full loaded dataset"""
        return self._df

    @property
    def df_train(self) -> pd.DataFrame:
        """Return the dataset for training only"""
        return self._df_train

    @property
    def df_val(self) -> pd.DataFrame:
        """Return the dataset for validation only"""
        return self._df_val

    @property
    def df_test(self) -> pd.DataFrame:
        """Return the dataset for training only"""
        return self._df_test

    @property
    def max_seq_len(self) -> int:
        """Longest sequence length"""
        return self._max_seq_len


def split_protrain_loader(
    dataset_path: str,
    encoder_name: str,
    reset_param: bool = False,
    resample_param: bool = False,
    embed_batch_size: int = 128,
    flatten_emb: bool | str = False,
    embed_folder: str | None = None,
    embed_layer: int | None = None,
    seq_start_idx: bool | int = False,
    seq_end_idx: bool | int = False,
    subset_list: list[str] = ["train", "val", "test"],
    loader_batch_size: int = 64,
    worker_seed: int = RAND_SEED,
    if_encode_all: bool = True,
    **encoder_params,
):

    """
    A function encode and load the data from a path

    Args:
    - dataset_path: str, full path to the dataset, in pkl or panda readable format, ie
        "data/proeng/gb1/low_vs_high.csv"
        columns include: sequence, target, set, validation,
        mut_name (optional), mut_numb (optional)
    - encoder_name: str, the name of the encoder
    - reset_param: bool = False, if update the full model to xavier_uniform_
    - resample_param: bool = False, if update the full model to xavier_normal_
    - embed_batch_size: int, set to 0 to encode all in a single batch
    - flatten_emb: bool or str, if and how (one of ["max", "mean"]) to flatten the embedding
    - embed_folder: str = None, path to presaved embedding
    - seq_start_idx: bool | int = False, the index for the start of the sequence
    - seq_end_idx: bool | int = False, the index for the end of the sequence
    - subset_list: list of str, train, val, test
    - loader_batch_size: int, the batch size for train, val, and test dataloader
    - worker_seed: int, the seed for dataloader
    - if_encode_all: bool = True, if encode full dataset all layers on the fly
    - encoder_params: kwarg, additional parameters for encoding
    """

    assert set(subset_list) <= set(
        ["train", "val", "test"]
    ), "subset_list can only contain terms with in be 'train', 'val', or 'test'"

    # specify no shuffling for validation and test
    if_shuffle_list = [True if subset == "train" else False for subset in subset_list]

    return (
        DataLoader(
            dataset=ProtranDataset(
                dataset_path=dataset_path,
                subset=subset,
                encoder_name=encoder_name,
                reset_param=reset_param,
                resample_param=resample_param,
                embed_batch_size=embed_batch_size,
                flatten_emb=flatten_emb,
                embed_folder=embed_folder,
                embed_layer=embed_layer,
                seq_start_idx=seq_start_idx,
                seq_end_idx=seq_end_idx,
                if_encode_all=if_encode_all,
                **encoder_params,
            ),
            batch_size=loader_batch_size,
            shuffle=if_shuffle,
            worker_init_fn=worker_seed,
        )
        for subset, if_shuffle in zip(subset_list, if_shuffle_list)
    )

In [63]:
"""A script with model training and testing details assuming"""

from __future__ import annotations

import random
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader
from tqdm import tqdm

from sklearn.metrics import mean_squared_error, log_loss, accuracy_score, roc_auc_score
from sklearn.preprocessing import LabelEncoder

from scr.params.sys import RAND_SEED, DEVICE

# seed everything
random.seed(RAND_SEED)
np.random.seed(RAND_SEED)
torch.manual_seed(RAND_SEED)
torch.cuda.manual_seed(RAND_SEED)
torch.cuda.manual_seed_all(RAND_SEED)
torch.backends.cudnn.deterministic = True


def get_x_y(
    model, device, batch, embed_layer: int,
):
    """
    A function process x and y from the loader

    Args:
    -

    Returns:
    - x
    - y
    """

    # for each batch: y, sequence, mut_name, mut_numb, [layer0, ...]
    # or: y, seuqence, mut_name, mut_numb, layer0, ...
    embs = batch[4]
    if torch.is_tensor(embs):
        x = embs
    else:
        x = embs[embed_layer]
    y = batch[0]

    """
    # process y depends on model type
    # annotation classification
    if model.model_name == "LinearClassifier":
        le = LabelEncoder()
        y = le.fit_transform(y.flatten())
    """

    # ss3 / ss8 type
    """if model.model_name == "MultiLabelMultiClass":
        # convert the y into np.arrays with -1 padding to the same length
        y = np.stack(
            [
                np.pad(i, pad_width=(0, x.shape[1] - len(i)), constant_values=-1,)
                for i in y
            ]
        )"""
    
    print("x shape for batch")
    print(x.shape, x.dtype)

    if len(y.shape) == 3:
        y = torch.squeeze(y)
    x = x.to(torch.float32)
    y = y.to(torch.float32)
    """if not torch.is_floating_point(y):
        y = y.to(x.dtype)"""
    print("print y shape for batch")
    print(y.shape, y.dtype)
    return x.to(device, non_blocking=True), y.to(device, non_blocking=True)


def run_epoch(
    model: nn.Module,
    loader: DataLoader,
    encoder_name: str,
    embed_layer: int,
    reset_param: bool = False,
    resample_param: bool = False,
    embed_batch_size: int = 0,
    flatten_emb: bool | str = False,
    # if_encode_all: bool = True,
    device: torch.device | str = DEVICE,
    criterion: nn.Module | None = None,
    optimizer: torch.optim.Optimizer | None = None,
    **encoder_params,
) -> float:

    """
    Runs one epoch.
    
    Args:
    - model: nn.Module, already moved to device
    - loader: torch.utils.data.DataLoader
    - device: torch.device or str
    - criterion: optional nn.Module, loss function, already moved to device
    - optimizer: optional torch.optim.Optimizer, must also provide criterion,
        only provided for training

    Returns: 
    - float, average loss over batches
    """
    if optimizer is not None:
        assert criterion is not None
        model.train()
        is_train = True
    else:
        model.eval()
        is_train = False

    cum_loss = 0.0

    with torch.set_grad_enabled(is_train):
        # if not if_encode_all:
        # for each batch: y, sequence, mut_name, mut_numb, [layer0, ...]

        for batch in loader:
            print("run epoch...")

            x, y = get_x_y(model, device, batch, embed_layer)

            """
            x = batch[4][embed_layer]
            y = batch[0]

            # process y depends on model type
            # annotation classification
            if model.model_name == "LinearClassifier":
                le = LabelEncoder()
                y = le.fit_transform(y.flatten())
            # ss3 / ss8 type
            elif model.model_name == "MultiLabelMultiClass":
                # convert the y into np.arrays with -1 padding to the same length
                y = np.stack(
                    [
                        np.pad(
                            np.array(i[1:-1].split(", ")),
                            pad_width=(0, x.shape[1] - len(i)),
                            constant_values=-1,
                        )
                        for i in y
                    ]
                )

            x, y = x.to(device, non_blocking=True), y.to(device, non_blocking=True)
            """
            print(model)
            outputs = model(x)
            print("run epoch")
            print(f"run epoch output size {outputs.shape}")
            print("y shape and (np.arange(y.max()+1) == y[...,None])")
            print(y.shape, (torch.arange(y.max()+1) == y[...,None]).to(torch.float32).shape)

            if criterion is not None:
                if model.model_name == "LinearRegression":
                    loss = criterion(outputs, y.float())
                elif model.model_name == "LinearClassifier":
                    loss = criterion(outputs, y.squeeze())
                elif model.model_name == "MultiLabelMultiClass":
                    loss = criterion(outputs, (torch.arange(y.max()+1) == y[...,None]).to(torch.float32))
                    # (np.arange(y.max()+1) == y[...,None]).astype(int)

                if optimizer is not None:
                    optimizer.zero_grad()
                    loss.backward()
                    optimizer.step()

                cum_loss += loss.item()

    return cum_loss / len(loader)


def train(
    model: nn.Module,
    criterion: nn.Module,
    train_loader: DataLoader,
    val_loader: DataLoader,
    encoder_name: str,
    embed_layer: int,
    reset_param: bool = False,
    resample_param: bool = False,
    embed_batch_size: int = 0,
    flatten_emb: bool | str = False,
    device: torch.device | str = DEVICE,
    learning_rate: float = 1e-4,
    lr_decay: float = 0.1,
    epochs: int = 100,
    early_stop: bool = True,
    tolerance: int = 10,
    min_epoch: int = 5,
    **encoder_params,
) -> tuple[np.ndarray, np.ndarray]:

    """
    Args:
    - model: nn.Module, already moved to device
    - train_loader: torch.utils.data.DataLoader, 
    - val_loader: torch.utils.data.DataLoader, 
    - criterion: nn.Module, loss function, already moved to device
    - device: torch.device or str
    - learning_rate: float
    - lr_decay: float, factor by which to decay LR on plateau
    - epochs: int, number of epochs to train for
    - early_stop: bool = True,

    Returns: 
    - tuple of np.ndarray, (train_losses, val_losses)
        train/val_losses: np.ndarray, shape [epochs], entries are average loss
        over batches for that epoch
    """

    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", factor=lr_decay
    )

    train_losses = np.zeros(epochs)
    val_losses = np.zeros(epochs)

    # init for early stopping
    counter = 0
    min_val_loss = np.Inf
    print("inside train before run_epoch")

    for epoch in tqdm(range(epochs)):

        train_losses[epoch] = run_epoch(
            model=model,
            loader=train_loader,
            encoder_name=encoder_name,
            embed_layer=embed_layer,
            reset_param=reset_param,
            resample_param=resample_param,
            embed_batch_size=embed_batch_size,
            flatten_emb=flatten_emb,
            device=device,
            criterion=criterion,
            optimizer=optimizer,
            **encoder_params,
        )

        val_loss = run_epoch(
            model=model,
            loader=val_loader,
            encoder_name=encoder_name,
            embed_layer=embed_layer,
            reset_param=reset_param,
            resample_param=resample_param,
            embed_batch_size=embed_batch_size,
            flatten_emb=flatten_emb,
            device=device,
            criterion=criterion,
            optimizer=None,
            **encoder_params,
        )
        val_losses[epoch] = val_loss

        scheduler.step(val_loss)

        if early_stop:
            # when val loss decrease, reset min loss and counter
            if val_loss < min_val_loss:
                min_val_loss = val_loss
                counter = 0
            else:
                counter += 1

            if epoch > min_epoch and counter == tolerance:
                break

    return train_losses, val_losses


def test(
    model: nn.Module,
    loader: DataLoader,
    embed_layer: int,
    criterion: nn.Module | None,
    device: torch.device | str = DEVICE,
    print_every: int = 1000,
) -> tuple[float, np.ndarray, np.ndarray]:
    """
    Runs one epoch of testing, returning predictions and labels.
    
    Args:
    - model: nn.Module, already moved to device
    - device: torch.device or str
    - loader: torch.utils.data.DataLoader
    - criterion: optional nn.Module, loss function, already moved to device
    - print_every: int, how often (number of batches) to print avg loss
    
    Returns: tuple (avg_loss, preds, labels)
    - avg_loss: float, average loss per training example 
    - preds: np.ndarray, shape [num_examples, ...], predictions over dataset
    - labels: np.ndarray, shape [num_examples, ...], dataset labels
    """
    model.eval()
    msg = "[{step:5d}] loss: {loss:.3f}"

    cum_loss = 0.0

    pred_probs = []
    pred_classes = []
    labels = []

    with torch.no_grad():

        for i, batch in enumerate(tqdm(loader)):
            # for each batch: y, sequence, mut_name, mut_numb, [layer0, ...]
            x, y = get_x_y(model, device, batch, embed_layer)

            """
            x = batch[4][embed_layer]
            y = batch[0]

            x, y = x.to(device, non_blocking=True), y.to(device, non_blocking=True)
            """
            print("before model(x)")

            # forward + backward + optimize
            outputs = model(x)
            print("after model(x) give pred shape")

            print(outputs.shape)

            # append results
            labels.append(y.detach().cpu().squeeze().numpy())

            # append class
            if model.model_name == "LinearClassifier" or "MultiLabelMultiClass":
                pred_classes.append(
                    outputs.detach()
                    .cpu()
                    .data.max(1, keepdim=True)[1]
                    .squeeze()
                    .numpy()
                )
                # pred_probs.append(outputs.detach().cpu().squeeze().numpy())
            # else:
            pred_probs.append(outputs.detach().cpu().squeeze().numpy())

            if criterion is not None:
                if model.model_name == "LinearRegression":
                    loss = criterion(outputs, y)
                elif model.model_name == "LinearClassifier" or "MultiLabelMultiClass":
                    loss = criterion(outputs, y.squeeze())
                cum_loss += loss.item()

                if ((i + 1) % print_every == 0) or (i + 1 == len(loader)):
                    tqdm.write(msg.format(step=i + 1, loss=cum_loss / len(loader)))

    avg_loss = cum_loss / len(loader)

    if pred_classes == []:
        pred_classes_conc = pred_classes
    else:
        pred_classes_conc = np.concatenate(pred_classes)

    return (
        avg_loss,
        np.concatenate(pred_probs),
        pred_classes_conc,
        np.concatenate(labels),
    )

In [65]:
"""Script for running pytorch models"""

from __future__ import annotations

import os
from tqdm import tqdm
from concurrent import futures

import torch
import torch.nn as nn

from sklearn.metrics import ndcg_score, accuracy_score, roc_auc_score

from scipy.stats import spearmanr

from scr.params.aa import AA_NUMB
from scr.params.sys import RAND_SEED, DEVICE
from scr.params.emb import TRANSFORMER_INFO, CARP_INFO, MAX_SEQ_LEN

# from scr.preprocess.data_process import split_protrain_loader, DatasetInfo
from scr.encoding.encoding_classes import OnehotEncoder, ESMEncoder, CARPEncoder, get_emb_info
# from scr.model.pytorch_model import LinearRegression, LinearClassifier

# from scr.model.train_test import train, test
from scr.vis.learning_vis import plot_lc
from scr.utils import get_folder_file_names, pickle_save, get_default_output_path


class Run_Pytorch:
    def __init__(
        self,
        dataset_path: str,
        encoder_name: str,
        reset_param: bool = False,
        resample_param: bool = False,
        embed_batch_size: int = 128,
        flatten_emb: bool | str = False,
        embed_folder: str | None = None,
        seq_start_idx: bool | int = False,
        seq_end_idx: bool | int = False,
        loader_batch_size: int = 64,
        worker_seed: int = RAND_SEED,
        if_encode_all: bool = True,
        if_multiprocess: bool = False,
        learning_rate: float = 1e-4,
        lr_decay: float = 0.1,
        epochs: int = 100,
        early_stop: bool = True,
        tolerance: int = 10,
        min_epoch: int = 5,
        device: torch.device | str = DEVICE,
        all_plot_folder: str = "results/learning_curves",
        all_result_folder: str = "results/train_val_test",
        **encoder_params,
    ) -> None:

        """
        A function for running pytorch model

        Args:
        - dataset_path: str, full path to the dataset, in pkl or panda readable format
            columns include: sequence, target, set, validation, mut_name (optional), mut_numb (optional)
        - encoder_name: str, the name of the encoder
        
        - embed_batch_size: int, set to 0 to encode all in a single batch
        - flatten_emb: bool or str, if and how (one of ["max", "mean"]) to flatten the embedding
        - embed_folder: str = None, path to presaved embedding
        - seq_start_idx: bool | int = False, the index for the start of the sequence
        - seq_end_idx: bool | int = False, the index for the end of the sequence
        - loader_batch_size: int, the batch size for train, val, and test dataloader
        - worker_seed: int, the seed for dataloader
        - learning_rate: float
        - lr_decay: float, factor by which to decay LR on plateau
        - epochs: int, number of epochs to train for
        - device: torch.device or str
        - all_plot_folder: str, the parent folder path for saving all the learning curves
        - all_result_folder: str = "results/train_val_test", the parent folder for all results
        - encoder_params: kwarg, additional parameters for encoding

        Returns:
        - result_dict: dict, with the keys and dict values
            "losses": {"train_losses": np.ndarray, "val_losses": np.ndarray}
            "train": {"mse": float, 
                    "pred": np.ndarray,
                    "true": np.ndarray,
                    "ndcg": float,
                    "rho": SpearmanrResults(correlation=float, pvalue=float)}
            "val":   {"mse": float, 
                    "pred": np.ndarray,
                    "true": np.ndarray,
                    "ndcg": float,
                    "rho": SpearmanrResults(correlation=float, pvalue=float)}
            "test":  {"mse": float, 
                    "pred": np.ndarray,
                    "true": np.ndarray,
                    "ndcg": float,
                    "rho": SpearmanrResults(correlation=float, pvalue=float)}

        """

        self._dataset_path = dataset_path
        self._encoder_name = encoder_name

        if self._encoder_name not in (list(TRANSFORMER_INFO.keys()) + list(CARP_INFO.keys())):
            self._encoder_name = "onehot"

        self._reset_param = reset_param
        self._resample_param = resample_param
        self._embed_batch_size = embed_batch_size
        self._flatten_emb = flatten_emb

        self._learning_rate = learning_rate
        self._lr_decay = lr_decay
        self._epochs = epochs
        self._early_stop = early_stop
        self._tolerance = tolerance
        self._min_epoch = min_epoch
        self._device = device
        self._all_plot_folder = all_plot_folder
        self._all_result_folder = all_result_folder
        self._encoder_params = encoder_params

        self._ds_info = DatasetInfo(self._dataset_path)
        self._model_type = self._ds_info.model_type
        self._numb_class = self._ds_info.numb_class

        self._train_loader, self._val_loader, self._test_loader = split_protrain_loader(
            dataset_path=self._dataset_path,
            encoder_name=self._encoder_name,
            reset_param=self._reset_param,
            resample_param=self._resample_param,
            embed_batch_size=self._embed_batch_size,
            flatten_emb=self._flatten_emb,
            embed_folder=embed_folder,
            seq_start_idx=seq_start_idx,
            seq_end_idx=seq_end_idx,
            subset_list=["train", "val", "test"],
            loader_batch_size=loader_batch_size,
            worker_seed=worker_seed,
            if_encode_all=if_encode_all,
            **encoder_params,
        )

        encoder_name, encoder_class, total_emb_layer = get_emb_info(encoder_name)

        if encoder_class == ESMEncoder:
            self._encoder_info_dict = TRANSFORMER_INFO
        elif encoder_class == CARPEncoder:
            self._encoder_info_dict = CARP_INFO
        elif encoder_class == OnehotEncoder:
            #TODO aultoto
            if self._flatten_emb == False:
                self._encoder_info_dict = {"onehot": (AA_NUMB, )}
            else:
                self._encoder_info_dict = {"onehot": (MAX_SEQ_LEN*22, )}

        if if_multiprocess:
            print("Running different emb layer in parallel...")
            # add the thredpool max_workers=None
            with futures.ProcessPoolExecutor(max_workers=os.cpu_count() - 1) as pool:
                # for each layer train the model and save the model
                for embed_layer in tqdm(range(total_emb_layer)):
                    pool.submit(self.run_pytorch_layer, embed_layer)

        else:
            for embed_layer in range(total_emb_layer):
                print(f"Running pytorch model for layer {embed_layer}")
                self.run_pytorch_layer(embed_layer)

    def run_pytorch_layer(self, embed_layer):

        # init model based on datasets
        if self._model_type == "LinearRegression":
            model = LinearRegression(
                input_dim=self._encoder_info_dict[self._encoder_name][0], output_dim=1
            )
            criterion = nn.MSELoss()

        elif self._model_type == "LinearClassifier":
            model = LinearClassifier(
                input_dim=self._encoder_info_dict[self._encoder_name][0],
                numb_class=self._numb_class,
            )
            criterion = nn.CrossEntropyLoss()
        elif self._model_type == "MultiLabelMultiClass":
            model = MultiLabelMultiClass(
                input_dim=self._encoder_info_dict[self._encoder_name][0],
                numb_class=self._numb_class,
            )
            # criterion = nn.CrossEntropyLoss()
            criterion = nn.BCELoss()

        model.to(self._device, non_blocking=True)

        criterion.to(self._device, non_blocking=True)

        train_losses, val_losses = train(
            model=model,
            criterion=criterion,
            train_loader=self._train_loader,
            val_loader=self._val_loader,
            encoder_name=self._encoder_name,
            embed_layer=embed_layer,
            reset_param=self._reset_param,
            resample_param=self._resample_param,
            embed_batch_size=self._embed_batch_size,
            flatten_emb=self._flatten_emb,
            device=self._device,
            learning_rate=self._learning_rate,
            lr_decay=self._lr_decay,
            epochs=self._epochs,
            early_stop=self._early_stop,
            tolerance=self._tolerance,
            min_epoch=self._min_epoch,
            **self._encoder_params,
        )

        # record the losses
        result_dict = {
            "losses": {"train_losses": train_losses, "val_losses": val_losses}
        }

        plot_lc(
            train_losses=train_losses,
            val_losses=val_losses,
            dataset_path=self._dataset_path,
            encoder_name=self._encoder_name,
            embed_layer=embed_layer,
            flatten_emb=self._flatten_emb,
            all_plot_folder=get_default_output_path(self._all_plot_folder),
        )

        # now test the model with the test data
        for subset, loader in zip(
            ["train", "val", "test"],
            [self._train_loader, self._val_loader, self._test_loader],
        ):

            loss, pred, cls, true = test(
                model=model,
                loader=loader,
                embed_layer=embed_layer,
                device=self._device,
                criterion=criterion,
            )

            if model.model_name == "LinearRegression":
                result_dict[subset] = {
                    "mse": loss,
                    "pred": pred,
                    "true": true,
                    "ndcg": ndcg_score(true[None, :], pred[None, :]),
                    "rho": spearmanr(true, pred),
                }

            elif model.model_name == "LinearClassifier" or "MultiLabelMultiClass":
                result_dict[subset] = {
                    "cross-entropy": loss,
                    "pred": pred,
                    "true": true,
                    "acc": accuracy_score(true, cls),
                    "rocauc": roc_auc_score(
                        true,
                        nn.Softmax(dim=1)(torch.from_numpy(pred)).numpy(),
                        multi_class="ovr",
                    )
                    # "rocauc": eval_rocauc(true, pred),
                }

        dataset_subfolder, file_name = get_folder_file_names(
            parent_folder=get_default_output_path(self._all_result_folder),
            dataset_path=self._dataset_path,
            encoder_name=self._encoder_name,
            embed_layer=embed_layer,
            flatten_emb=self._flatten_emb,
        )

        print(f"Saving results for {file_name} to: {dataset_subfolder}...")
        pickle_save(
            what2save=result_dict,
            where2save=os.path.join(dataset_subfolder, file_name + ".pkl"),
        )

In [66]:
Run_Pytorch(
    dataset_path="data/structure/secondary_structure/casp12.csv",
    encoder_name="",
    reset_param = False,
    resample_param = False,
    embed_batch_size = 0,
    flatten_emb= False,
    embed_folder=None,
    seq_start_idx= False,
    seq_end_idx = False,
    loader_batch_size = 64,
    worker_seed = RAND_SEED,
    if_encode_all = True,
    learning_rate = 1e-4,
    lr_decay = 0.1,
    epochs = 50,
    early_stop = True,
    tolerance = 10,
    min_epoch = 5,
    device = DEVICE,
    all_plot_folder = "test/learning_curves",
    all_result_folder = "test/train_val_test",
    # **encoder_params,
    )

Generating onehot upto 0 layer embedding ...
Encoding all...
Converting ss3/ss8 into np.array...
print np_y shape for dataset
(8678, 1632)
Generating onehot upto 0 layer embedding ...
Encoding all...
Converting ss3/ss8 into np.array...
print np_y shape for dataset
(2170, 1228)


Generating onehot upto 0 layer embedding ...
Encoding all...
Converting ss3/ss8 into np.array...
print np_y shape for dataset
(21, 1494)
Running pytorch model for layer 0
inside train before run_epoch
run epoch...
x shape for batch
torch.Size([64, 1632, 23]) torch.float64
print y shape for batch
torch.Size([64, 1632]) torch.float32
MultiLabelMultiClass(
  (linear): Linear(in_features=23, out_features=4, bias=True)
  (softmax): Softmax(dim=2)
)
multilabel output inside forward
tensor([[[0.2546, 0.2946, 0.2337, 0.2171],
         [0.2622, 0.2425, 0.2515, 0.2438],
         [0.2748, 0.2466, 0.2417, 0.2369],
         ...,
         [0.2640, 0.2584, 0.2447, 0.2329],
         [0.2640, 0.2584, 0.2447, 0.2329],
         [0.2640, 0.2584, 0.2447, 0.2329]],

        [[0.2465, 0.2128, 0.2732, 0.2675],
         [0.2597, 0.2802, 0.2096, 0.2505],
         [0.2748, 0.2466, 0.2417, 0.2369],
         ...,
         [0.2640, 0.2584, 0.2447, 0.2329],
         [0.2640, 0.2584, 0.2447, 0.2329],
         [0.2640

  0%|          | 0/50 [00:07<?, ?it/s]


KeyboardInterrupt: 